# Generated by Django 3.0.7 on 2020-06-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=60, verbose_name='Empresa')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=25, verbose_name='Setor')),
            ],
            options={
                'db_table': 'setor',
            },
        ),
        migrations.CreateModel(
            name='contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('sobre_nome', models.CharField(max_length=60, verbose_name='Sobre Nome')),
                ('ramal', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ramal')),
                ('celular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.empresa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.setor')),
            ],
            options={
                'db_table': 'contato',
            },
        ),
    ]
